### ISSUE TITLE
documentation error

### ISSUE THREAD

**Issue by Pixilaxted-Fruit** [awesome-llama/image_format#2]
in the format specifications  part of the wiki it shows as
``
!"#$%&\'()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz{|}~
``
which incorrectly shows an extra \ but it should be 
``
!"#$%&'()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz{|}~
``
as in theUFT-8 documentation

**Comment by awesome-llama** [comment]
fixed

**Comment by awesome-llama** [comment]
fixed
